name: .NET

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Package
      run: |
        cd src/LinkManager.Api.GraphQL
        dotnet new tool-manifest
        dotnet tool install Amazon.Lambda.Tools
        dotnet lambda package
      artifacts:
        - src/LinkManager.Api.GraphQL/bin/serverless/deploy-package.zip
