name: .NET

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Package
      run: |
        cd src/LinkManager.Api.GraphQL
        dotnet new tool-manifest
        dotnet tool install Amazon.Lambda.Tools
        dotnet lambda package
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
          name: deploy-package.zip
          path: src/LinkManager.Api.GraphQL/bin/serverless/
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Download artifact  
      uses: actions/download-artifact@v2
      with:
        name: deploy-package.zip
        path: src/LinkManager.Api.GraphQL/bin/serverless/

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: src/LinkManager.Api.GraphQL/bin/serverless

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}    
    - name: Serverless deploy
      uses: serverless/github-action@v1
      with:
        args: deploy --stage prod --config src/LinkManager.Api.GraphQL/serverless.yml
